### ISSUE TITLE
Compatibility with actions/add-to-project

### ISSUE THREAD

**Issue by qwinters** [alstr/todo-to-issue-action#138]
GitHub now provides an official [actions/add-to-project](https://github.com/actions/add-to-project) action to triage new issues for Projects V2 (which is no longer a beta product). For some reason, issues created by todo-to-issue-action do not trigger this action when they are created/labeled. 

It would be nice to have this compatibility especially because then Projects V2 issue is not really something that `todo-to-issue-action` needs to provide

**Comment by alstr** [comment]
I've had a bit of a test of it and I can't get it to run either. Could it be that the issue opened event isn't triggered when called via the API? I created an issue manually and it did work however.

Also noteworthy, I incorporated the workflow into the existing TODO to Issue workflow, triggered on push, and it did run then, but then it complained that the issue was 'undefined' and didn't have the label `bug` (when it did). As it stands, I don't think there's anything specifically wrong with TODO to Issue stopping this from working, but I'm not sure why it doesn't. I think it's something to be investigated on their side.

It would be good to get it working as projects is an area in need of improvement, and it would save work. Any extra investigation would be helpful!

**Comment by qwinters** [comment]
Worth noting that it looks like the roadmap for GitHub projects actually includes better automation for adding to projects in this current quarter (so I imagine it will be generally available soon). See: https://github.com/github/roadmap/issues/576

I think this means we can actually close this for now and re-open if that automation that GitHub provides in the future doesn't work with `todo-to-issue-action`'s created issues
