### ISSUE TITLE
Bug: Action adds blank line instead of issue URL

### ISSUE THREAD

**Issue by ttrssreal** [alstr/todo-to-issue-action#249]
Hi! Ive just integrated this action and did an initial manual run, it seems to have worked for all but one of my TODO's, it adds a blank line instead of the issue URL (See: [the last patch listed in this commit](https://github.com/ttrssreal/nix-config/commit/926de46a2114fb4ce2cdc19041c06d0156e7d36a)).
The actual issue is created, just not linked.

[This is the job](https://github.com/ttrssreal/nix-config/actions/runs/12026205507/job/33524720748)
[This is the workflow](https://github.com/ttrssreal/nix-config/blob/8c7979f40f87cac6853e24169a346afb4c882665/.github/workflows/todo.yaml)

Thanks!

**Comment by ttrssreal** [comment]
Tried with latest(v5.1.5), issue persists D:

**Comment by alstr** [comment]
Hi, please can you try again with the latest version? There was an issue where the action was targeting an out of date image, which had some bugs that have since been resolved. If that doesn’t help I’ll look into it further. Thanks.

**Comment by ttrssreal** [comment]
Just tested now, instead of inserting a blank line it creates the gh issue and reports the error to stdout. [Heres the job](https://github.com/ttrssreal/test-todo-gh-action/actions/runs/12041633402/job/33573863216), and [this is the line it doesn't like](https://github.com/ttrssreal/test-todo-gh-action/blob/17526b5e073e38502ffb4e4657d258284a6a2c05/users/jess/default.nix#L32), syntactically I don't see anything wrong? Thanks

**Comment by alstr** [comment]
So the console reports one failure inserting the issue URL; did the others get inserted correctly?

@rgalonso Any thoughts on why the issue URL might not be being inserted?

**Comment by ttrssreal** [comment]
The others appear to be inserted correctly

**Comment by rgalonso** [comment]
This was tricky, but ultimately this failed because the app was instructed to insert a URL at a line that no longer exists at the line number where it was found. Let me explain.

The job was run on commit [c3e195f7](https://github.com/ttrssreal/test-todo-gh-action/commit/c3e195f7195ce7a93ff6325e0546400ed0867708), as shown in the [checkout log](https://github.com/ttrssreal/test-todo-gh-action/actions/runs/12041633402/job/33573863216#step:3:67). @ttrssreal, it looks like you set the `MANUAL_COMMIT_REF` input to [6449b61c](https://github.com/ttrssreal/test-todo-gh-action/commit/6449b61c9be5f91ceec240ce1f34e8520a4a265b), as shown in the [todo-to-issue job log](https://github.com/ttrssreal/test-todo-gh-action/actions/runs/12041633402/job/33573863216#step:4:21).

The problem comes from the fact that between those two commits, the file in question ([`users/jess/default.nix`](https://github.com/ttrssreal/test-todo-gh-action/blob/main/users/jess/default.nix)) was modified in commit [90b68841](https://github.com/ttrssreal/test-todo-gh-action/commit/90b68841f16aeaa2184d8f705270f9bac7b7662b#diff-5e1d4fbcee3ee3388de836f72fb547c00cecbf002ec7eba1df3928aa845f372f). Since `todo-to-issue` was run against the old (6449b61c) line numbering, when it went to insert the issue URL comment into the current file (c3e195f7), the line numbering wasn't as expected due to the changes of the intermediate commit (90b68841).

I understand the motivation for setting the `MANUAL_COMMIT_REF` input, but when combining that with `INSERT_ISSUE_URLS`, you can get tripped up like this. What I recommend for bootstrapping a new project like you're doing here is to instead change the `MANUAL_BASE_REF` input. That will then analyze the diff between that base ref and the _current_ commit and you won't run into this line numbering gotcha. The easiest thing is to set the base ref to your repository's first commit ([beed17f9](https://github.com/ttrssreal/test-todo-gh-action/commit/beed17f99815bb3f9ac01329a37e0a046a11f415)), but if you've got an especially deep commit history, you may want to choose some later reference.

Let me know if that helps!

@alstr, as an aside, maybe we should add a "bootstrapping" feature to help new users with historical TODOs ramp up? (If you agree, that clearly deserves its own issue/discussion.)

**Comment by ttrssreal** [comment]
> This was tricky, but ultimately this failed because the app was instructed to insert a URL at a line that no longer exists at the line number where it was found. Let me explain.
> 
> The job was run on commit [c3e195f7](https://github.com/ttrssreal/test-todo-gh-action/commit/c3e195f7195ce7a93ff6325e0546400ed0867708), as shown in the [checkout log](https://github.com/ttrssreal/test-todo-gh-action/actions/runs/12041633402/job/33573863216#step:3:67). @ttrssreal, it looks like you set the `MANUAL_COMMIT_REF` input to [6449b61c](https://github.com/ttrssreal/test-todo-gh-action/commit/6449b61c9be5f91ceec240ce1f34e8520a4a265b), as shown in the [todo-to-issue job log](https://github.com/ttrssreal/test-todo-gh-action/actions/runs/12041633402/job/33573863216#step:4:21).
> 
> The problem comes from the fact that between those two commits, the file in question ([`users/jess/default.nix`](https://github.com/ttrssreal/test-todo-gh-action/blob/main/users/jess/default.nix)) was modified in commit [90b68841](https://github.com/ttrssreal/test-todo-gh-action/commit/90b68841f16aeaa2184d8f705270f9bac7b7662b#diff-5e1d4fbcee3ee3388de836f72fb547c00cecbf002ec7eba1df3928aa845f372f). Since `todo-to-issue` was run against the old (6449b61c) line numbering, when it went to insert the issue URL comment into the current file (c3e195f7), the line numbering wasn't as expected due to the changes of the intermediate commit (90b68841).
> 
> I understand the motivation for setting the `MANUAL_COMMIT_REF` input, but when combining that with `INSERT_ISSUE_URLS`, you can get tripped up like this. What I recommend for bootstrapping a new project like you're doing here is to instead change the `MANUAL_BASE_REF` input. That will then analyze the diff between that base ref and the _current_ commit and you won't run into this line numbering gotcha. The easiest thing is to set the base ref to your repository's first commit ([beed17f9](https://github.com/ttrssreal/test-todo-gh-action/commit/beed17f99815bb3f9ac01329a37e0a046a11f415)), but if you've got an especially deep commit history, you may want to choose some later reference.
> 
> Let me know if that helps!
> 
> @alstr, as an aside, maybe we should add a "bootstrapping" feature to help new users with historical TODOs ramp up? (If you agree, that clearly deserves its own issue/discussion.)

Oh I see! that would make sense :sweat_smile:, thanks so much for your help :3

**Comment by alstr** [comment]
> This was tricky, but ultimately this failed because the app was instructed to insert a URL at a line that no longer exists at the line number where it was found. Let me explain.
> 
> The job was run on commit [c3e195f7](https://github.com/ttrssreal/test-todo-gh-action/commit/c3e195f7195ce7a93ff6325e0546400ed0867708), as shown in the [checkout log](https://github.com/ttrssreal/test-todo-gh-action/actions/runs/12041633402/job/33573863216#step:3:67). @ttrssreal, it looks like you set the `MANUAL_COMMIT_REF` input to [6449b61c](https://github.com/ttrssreal/test-todo-gh-action/commit/6449b61c9be5f91ceec240ce1f34e8520a4a265b), as shown in the [todo-to-issue job log](https://github.com/ttrssreal/test-todo-gh-action/actions/runs/12041633402/job/33573863216#step:4:21).
> 
> The problem comes from the fact that between those two commits, the file in question ([`users/jess/default.nix`](https://github.com/ttrssreal/test-todo-gh-action/blob/main/users/jess/default.nix)) was modified in commit [90b68841](https://github.com/ttrssreal/test-todo-gh-action/commit/90b68841f16aeaa2184d8f705270f9bac7b7662b#diff-5e1d4fbcee3ee3388de836f72fb547c00cecbf002ec7eba1df3928aa845f372f). Since `todo-to-issue` was run against the old (6449b61c) line numbering, when it went to insert the issue URL comment into the current file (c3e195f7), the line numbering wasn't as expected due to the changes of the intermediate commit (90b68841).
> 
> I understand the motivation for setting the `MANUAL_COMMIT_REF` input, but when combining that with `INSERT_ISSUE_URLS`, you can get tripped up like this. What I recommend for bootstrapping a new project like you're doing here is to instead change the `MANUAL_BASE_REF` input. That will then analyze the diff between that base ref and the _current_ commit and you won't run into this line numbering gotcha. The easiest thing is to set the base ref to your repository's first commit ([beed17f9](https://github.com/ttrssreal/test-todo-gh-action/commit/beed17f99815bb3f9ac01329a37e0a046a11f415)), but if you've got an especially deep commit history, you may want to choose some later reference.
> 
> Let me know if that helps!
> 
> @alstr, as an aside, maybe we should add a "bootstrapping" feature to help new users with historical TODOs ramp up? (If you agree, that clearly deserves its own issue/discussion.)

Thanks for the detailed explanation. I definitely agree with the feature to help new users import existing TODOs. It's been on the someday list for a while. The manual commit comparison feature was partly an attempt at that, but there's definitely scope to improve.

> I should add that while @ttrssreal's problem should be resolved by instead setting the base ref, I do agree that this is buggy behavior in that a blank line was inserted. It's one thing to report an error in the log (which it did), but it's another to insert anything other than the issue URL comment that was expected. Interestingly, I'm not able to replicate that error.
> 
> @alstr, I tested this locally (using `LocalClient` rather than `GitHubClient`). Issue URL comment insertion should be client-agnostic since it occurs in `main.py`. It's not clear to me why this blank line insertion occurred when running as an action but not when running locally, but the biggest difference I see is `GitHubClient` vs `LocalClient`, even though I wouldn't expect it to matter. Thoughts?

I think what might have happened is that the action originally ran against the `v5.0` image, i.e. before your bug fixes to the URL insertion. That was where the blank line insertion was coming from. Once I fixed the error in `action.yml` to bring the image in line with the current app version, that's when it errored rather than inserting a blank line. As far as I understand anyway, correct me if I'm wrong.

I will close this now as hopefully the original issue is solved; any related issues we can discuss elsewhere.

**Comment by rgalonso** [comment]
> I think what might have happened is that the action originally ran against the `v5.0` image, i.e. before your bug fixes to the URL insertion. That was where the blank line insertion was coming from. Once I fixed the error in `action.yml` to bring the image in line with the current app version, that's when it errored rather than inserting a blank line. As far as I understand anyway, correct me if I'm wrong.

Ah, yes, you're right. Taking that into account, I was able to replicate the blank line insertion using version v5.1 (which is the first version which has `LocalClient` and thus lets me test locally). While what I said in my earlier comment is still valid (regarding mixing `MANUAL_COMMIT_REF` with `INPUT_INSERT_ISSUE_URLS`), I'm now convinced this was really just another variation of #225. Running against commit [c3e195f7](https://github.com/ttrssreal/test-todo-gh-action/commit/c3e195f7195ce7a93ff6325e0546400ed0867708) and using commit [bf9d600d](https://github.com/ttrssreal/test-todo-gh-action/commit/bf9d600dde907eca47895cfe18e0b25d18ff7506) as the `MANUAL_BASE_REF`, the blank line is inserted. That is not surprising given that #225 wasn't yet fixed in v5.1. This was fixed in v5.1.1.

> I will close this now as hopefully the original issue is solved; any related issues we can discuss elsewhere.

Agreed.
