### ISSUE TITLE
No such file or directory: 'syntax.json'

### ISSUE THREAD

**Issue by bmcclure** [alstr/todo-to-issue-action#39]
I am attempting to use the latest example configuration to implement this action on my AutoHotKey project (https://github.com/VolantisDev/Launchpad), but I received an error on the action:

```
Traceback (most recent call last):
  File "/app/main.py", line 456, in <module>
    raw_issues = TodoParser().parse(last_diff)
  File "/app/main.py", line 190, in __init__
    with open('syntax.json', mode='r') as syntax_file:
FileNotFoundError: [Errno 2] No such file or directory: 'syntax.json'
```

GitHub does have language information for AutoHotKey so I thought it might work, but is the language the issue, did I miss a step by simply using the example config, or is this some other bug I am running up against?

Thank you!

**Comment by alstr** [comment]
Hey, thanks for the report.

The error there was caused by the action looking in your repo for the `syntax.json` file, rather than the workflow's. I've updated how that file is retrieved, and it should work now.

I can't see any obvious reason why AutoHotkey wouldn't work. I've added it to the syntax file as it wasn't there previously. If you want to try it you can update your workflow file to target `v3.0.1-beta`. Bear in mind that only TODOs on their own line are supported at the moment (though I am looking at that):

````autohotkey
; This is my comment.
````

I haven't been able to verify that this works yet, but if you want to try and let me know I can look into it further if necessary.

**Comment by bmcclure** [comment]
@alstr It works perfectly now, thanks so much for the quick assistance!

**Comment by alstr** [comment]
Great, thanks for letting me know.
