### ISSUE TITLE
Add blob of code around of the row where the TODO is

### ISSUE THREAD

**Issue by Jamminroot** [alstr/todo-to-issue-action#4]
Hey!

I was wondering if it's possible to add blobs of code around the `// TODO ` comment to an issue description (but not the row #)? That would reduce amount of tabs needed to be opened, and make context of auto-generated issue more visible.

```csharp
var myMagicDebugVariable = true;
// TODO Remove
if (myMagicDebugVariable) {
```

Thanks for a great tool!

**Comment by alstr** [comment]
Hey there @Jamminroot, thanks for the kind words.

I think this should be doable relatively easily. When the app cycles through the lines in each hunk, I could keep the lines in an array. If the app finds a TODO in a given hunk, it could join the lines and add it to the issue body. Without testing it out, it would probably be easier to include the entire hunk rather than a line either side. Plus, it's sort of subjective as to whether one line either side is useful, or two lines, or three, etc. But I'll do some testing and see. Anyway, I'll have a look next time I get chance to work on this.

**Comment by alstr** [comment]
I've integrated this in 84d22beb97c294332641f364465fb0aa18c6da5c. You should now get a code snippet in your created issues (like below). I've also a request to GitHub's [languages file](https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml) so the snippet can be highlighted correctly for the language. If you encounter any issues let me know!

<img width="758" alt="Screenshot 2020-04-17 at 16 19 00" src="https://user-images.githubusercontent.com/11612438/79587441-743b1680-80ca-11ea-91fc-c32bf29dbd4c.png">
