### ISSUE TITLE
Action is not creating issues as expected

### ISSUE THREAD

**Issue by Magnum97** [alstr/todo-to-issue-action#5]
Hello and first off thank you for writing this.
I added this workflow to a project today and it did run without error but did not create any issues as I expected that it would. I have tried two versions, one as published in your Readme with `# TODO` and `#` as the comment tag. I have some `# TODO ...` items in a YAML file. I also ran a version with `// TODO` and `//` as the tag for Java files, which again ran successfully but failed to create issues. Do the files with TODO items in question need to be pushed with/after the workflow is in place? That is the only problem I can think of. My first run was pushed with TODO items but failed due to a YAML format error. I fixed it and pushed again abut did not get issues.

My workflow: https://hatebin.com/ccarzcfcdu
Examples of my TODO items: 
  YAML: `# This is for future version todo Add food modifiers` 
 Java: `chanceModifier = foodCalc(target, hand); // todo increase chance of egg/fertile egg by type of food.`

Any guideance would be greatly appreciated.

**Comment by alstr** [comment]
Hi @Magnum97, thanks getting in touch. Sorry for the issues you’ve had! I’ll do some testing based on the examples you’ve provided and get back to you ASAP. My initial guesses, however, are:

* In the YAML example, it’s not picked up because the keyword label is not at the start of the comment.
* In the Java example, it’s not picked up because the keyword is lowercase (vs uppercase in the workflow file).

The syntax requirements are a bit specific at the moment but it’s something that I can be look at relaxing going forward.

If you do want to try reformatting your code you can try:

`# TODO Add food modifiers in future version.`

`// TODO Increase chance of egg/fertile egg by type of food.`

Otherwise I’ll get back to you when I’ve been able to replicate it! Thanks.

**Comment by Magnum97** [comment]
Ha! Beautiful - I now have 10 issues :laughing: Thank you for the tip. Yeah I TODO for readme would be awesome but I know I hate writing documentation so I understand. Again thank you for this tool and if you are interested in how it worked for me this is the repo I am using it in: https://github.com/Magnum97/BreedablePetsMC/blob/dev/src/main/java/me/magnum/breedablepets/listeners/BreedListener.java#L76
Java examples, obviously and it even worked on my yaml:
https://github.com/Magnum97/BreedablePetsMC/blob/dev/src/main/resources/config.yml#L14

It is great having the code snippet included. Again, thank you very much. Great tool!

**Comment by alstr** [comment]
That’s great, glad to hear it’s resolved. Thanks for your feedback! If you do encounter any other issues or have further ideas then let me know! 😀
