### ISSUE TITLE
Weird brackets on PR title

### ISSUE THREAD

**Issue by milewski** [alstr/todo-to-issue-action#67]
Hi, just passing by to report an issue with the title parser

![image](https://user-images.githubusercontent.com/2874967/127974311-b197b357-c93e-4aa1-827f-0bce5b03d831.png)

**Comment by alstr** [comment]
Thanks for the report. I was able to replicate this. The problem was that the parentheses in the TODO text was causing the parser to think that this was a reference to prepend to the issue title in square brackets as [described here](https://github.com/alstr/todo-to-issue-action#reference). Hopefully it should work now but if it happens again do let me know. Apologies for the inconvenience. You should be able to manually update the title of that issue without any problems.
