### ISSUE TITLE
Problem with multiple todos directly below each other

### ISSUE THREAD

**Issue by phartenfeller** [alstr/todo-to-issue-action#7]
First of all thank you very much for this action! 

It seems like there is a problem when you have multiple todos directly below each other:

```
Does not work:
// TODO todo1
// TODO todo2

Empty line fixes this:
// TODO todo1

// TODO todo2
```

I guess it is a rare case to have multiple ones but for me it created no GH-issues at all even though there where single todos in different places. So I guess this crashes the process.

I simply inserted empty lines between the comments to make it work again but I just wanted you (or others with the same issue) to know of this bug.

**Comment by alstr** [comment]
Hi Philipp. Thanks for letting me know. I’ll aim to take a look tomorrow and hopefully get a fix out.

**Comment by alstr** [comment]
Hi. :wave:

I've done some testing but I can't reproduce this at the moment. I added two TODOs on consecutive lines and they were both picked up. Would you be able to share a code/diff snippet that caused this issue for you?

The only thing I can think of is that if the TODOs were added in a previously pushed commit, they wouldn't have been picked up in your next one as only newly added TODOs are recognised, not existing ones. But from the sounds of it that's not the case.

If the new line was the issue, at the very least I would have expected the first TODO to be picked up, so it might be something else, but I'll look into it further if you can provide additional details.

Thanks!

**Comment by phartenfeller** [comment]
Hi, thank you for your fast response.

This is the code that caused the error: https://github.com/phartenfeller/plsql-parser/blob/73892710febe9c80afa6fa69f1609098d5af1b88/chevrotain/rules.js#L583 . The output of the action is here: https://github.com/phartenfeller/plsql-parser/runs/686302161?check_suite_focus=true 

After that I deleted the todos on the referenced part and your action created issues for the other 2 todos in the file which were not picked up before which lets me guess it crashed the action somehow (although it shows a success). Here is the code https://github.com/phartenfeller/plsql-parser/blob/defe4825f83bbe79d4a394f307a6af51ece03d46/chevrotain/rules.js#L581 and the action output: https://github.com/phartenfeller/plsql-parser/runs/686353633?check_suite_focus=true 

In the current release it works with empty lines between the Todos: https://github.com/phartenfeller/plsql-parser/blob/master/chevrotain/rules.js#L582 . Here is the action result: https://github.com/phartenfeller/plsql-parser/runs/686360506?check_suite_focus=true

Maybe it could fail with more than 2 todos beneath each other or I missed something else I changed.

**Comment by alstr** [comment]
Hey Philipp. Thanks very much for sharing that.

For the action run you shared, it looks like your `LABEL` input is defined as [`\\ TODO:` in the workflow file](https://github.com/phartenfeller/plsql-parser/actions/runs/108437620/workflow), but `rules.js` uses `\\ TODO` (note the missing colon).

I updated that and ran the action on your file and it worked with these consecutive TODOs:

<img width="586" alt="Screenshot 2020-05-19 at 12 36 23" src="https://user-images.githubusercontent.com/11612438/82325573-5d425980-99d3-11ea-9938-7fd39457bac0.png">

I've accidentally included a colon a few times myself, so I've released an update that will allow for a colon, space, or a colon and space after the `LABEL`.

I also noticed a few errors in the action output caused by the inputs not being defined in the `action.yml` file, so I've corrected that.

I think everything should be okay now. If you have any further issues do let me know.
