### ISSUE TITLE
Request for sql to be added? 

### ISSUE THREAD

**Issue by ConnorWilloughby2** [alstr/todo-to-issue-action#74]
Hi Team, 

This repo is fantastic im currently adding it to all of my repos as its just so bloody useful! That being said one of my main repos is just a huge stash of .sql files that i use. It would be awesome to see todos also process this extension! 

Thanks!

**Comment by alstr** [comment]
Hi, thanks for the feedback.

Yes, this is definitely possible. I just had a quick look at adding support for it and I noticed a potential issue: `.sql` appears as an extension in multiple languages in GitHub's `languages.yaml`. At the moment, I think it defaults to the first language, which would be PLSQL, rather than plain SQL. It might still work in this case if the comment syntax is the same, but we should probably fix that to avoid mixups in similar situations.

**Comment by ConnorWilloughby2** [comment]
To be honest comment syntax is identical as far as im aware so whilst its not perfect it would get the job done!

Thanks so much!

**Comment by alstr** [comment]
I actually misremembered how the aciton works. There shouldn't be a problem. I've added support for it now, just use the latest version. Hope it works!
