### ISSUE TITLE
Tests for ABAP

### ISSUE THREAD

**Issue by mbtools** [alstr/todo-to-issue-action#87]
I tried the four different comments mentioned in #85. 3 of the 4 work beautifully. However, it did not create a todo issue for one of them.

Test repo:
https://github.com/mbtools/TEST-Todo-to-Issue

Commit where I was expecting a new issue:
https://github.com/mbtools/TEST-Todo-to-Issue/commit/c590a0f025e25af4df071f8eb662fbb61625d4bd

```abap
WRITE moo. " TODO This is an end-of-line to-do
```

Feel free to add new commits

**Comment by alstr** [comment]
Thanks, I'll take a look soon. `"` is an unusual comment identifier I've never used before, so I'll do a bit of investigation, but I'm confident I can get it working.

**Comment by alstr** [comment]
It seems like the problem was that end-of-line TODOs were not being picked up, because the regex was checking only the start of the line. I've updated it so that end-of-line should be checked now also, and from my tests it seems to be working with all ABAP comment types. It's still maybe a little experimental as I haven't yet tested extensively. Let me know if that resolves things for you.

**Comment by mbtools** [comment]
Confirming that it works with @master:

![image](https://user-images.githubusercontent.com/59966492/141308988-34b5195f-bfce-44c8-bfde-fe584ed9c40e.png)
