### ISSUE TITLE
Add option to customize issue content

### ISSUE THREAD

**Issue by mbtools** [alstr/todo-to-issue-action#91]
There is quite some repetition in the content of a todo-issue:

![image](https://user-images.githubusercontent.com/59966492/141320688-4e33e656-5b00-4bc7-aeb9-ca4a7e732df8.png)

The TODO comment actually appears 3 times. It would be nice to configure the action and decide which parts should be included:

1. Plain text
2. Link to blob
3. Hunk
4. Issue ID  

I would say, by default, 1 and 2 should be on, 3 and 4 should be off.

**Comment by alstr** [comment]
Yes, the content is duplicated somewhat. GitHub automatically inserts the code snippet for the link to the line in the code, but yes the hunk could be optional.

The issue ID was implemented a long while ago to help identify duplicate issues. Sometimes when multiple events are triggered, the action can come across a TODO more than once, so it creates a hash of the issue body and searches to see if this is present in any existing issues. Not ideal, but it's tricky when the action is stateless so doesn't know what it has processed before and what it hasn't. We could maybe just directly compare the body text rather than hash it.

**Comment by alstr** [comment]
I've just added support for custom issue templates. You can specify a Markdown-style template in `workflow.yml` by defining `ISSUE_TEMPLATE`. You can inject the title, body, url or code snippet as below:

`ISSUE_TEMPLATE: "This is my issue title: **{{ title }}**\n\nThis is my issue body: **{{ body }}**\n\nThis is my code URL: **{{ url }}**\n\nThis is my snippet:\n\n{{ snippet }}"`

If no template is specified, the default layout is used, however, the TODO hash has been removed (a straightforward title comparison is now used to check if an issue already exists), and the TODO title is no longer duplicated in the body.

Will release it shortly.

**Comment by mbtools** [comment]
Excellent. Ty
