### ISSUE TITLE
Reference = assignee

### ISSUE THREAD

**Issue by RicoP** [alstr/todo-to-issue-action#94]
I use the pattern 

```// TODO(RicoP) bla``` 

very commonly to refer to a username. Is there a option to automatically add a reference to the assignees list?

**Comment by alstr** [comment]
Not at the moment, but this is certainly doable. We can't treat references as assignees by default as the [reference may not always be an assignee](https://google.github.io/styleguide/cppguide.html#TODO_Comments):

```
// TODO(kl@gmail.com): Use a "*" here for concatenation operator.
// TODO(Zeke) change this to use relations.
// TODO(bug 12345): remove the "Last visitors" feature.
```

However, the workflow file could take an optional input, say `REFERENCE_ASSIGNEE`, which if `true` would treat all references as assignees.

If you'd like to submit a PR feel free, otherwise I'll take a look when I get chance.

**Comment by silopolis** [comment]
As Google's Style Guide makes it ambiguous, I'd favor [Conventional Commits'](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-scope-and--to-draw-attention-to-breaking-change) more precise use as scope reference.
However, scope being defined as 'section of the codebase' there, I wonder if it could be that useful here.

Of course, a config toggle could be nice, but then you may find a chain of requests to have one for all possible usages. In which case, a config mapping option like `reference: assignee` or `reference: issue` may be better.

**Comment by alstr** [comment]
Will combine with #123 so hopefully the reference can take either an assignee or issue ID.
